### ISSUE TITLE
Does not warn/fail on nuget execution status

### ISSUE THREAD

**Issue by mattkenn4545** [Inedo/bmx-nuget#21]
If the nuget processe(s) fail or go warning there does not appear to be any mechanism to determine this.  

Looking at http://inedo.com/support/sdk-reference/otter/Inedo.Otter.Extensibility.Operations/IOperationExecutionContext there does appear to be a way to get the execution status of an execution.

**Comment by BenLubar** [comment]
If the operation uses the "error" log level, the OtterScript can catch that using a try-catch block.

You can get the status from the context using the [ExecutionStatus](http://inedo.com/support/sdk-reference/otter/Inedo.Otter.Extensibility.Operations/IOperationExecutionContext/ExecutionStatus) property. Setting the status is done via `this.LogWarning`, `this.LogError`, etc., or by throwing an uncaught exception.

**Comment by mattkenn4545** [comment]
The nuget extension does not seem to log at anything other than DEBUG.  Here is a the log logmessages of one of the executions.  

`DEBUG: 2017-08-08 18:57:13Z - Using LocalAgent agent on localhost
INFO : 2017-08-08 18:57:13Z - Installing packages for projects in C:\BuildMaster\Workspace\ThingCompany.InventoryManager to C:\BuildMaster\Workspace\ThingCompany.InventoryManager\src\packages...
INFO : 2017-08-08 18:57:13Z - Finding packages.config files in C:\BuildMaster\Workspace\ThingCompany.InventoryManager...
INFO : 2017-08-08 18:57:13Z - Installing packages for C:\BuildMaster\Workspace\ThingCompany.InventoryManager\src\ThingCompany.InventoryManager\packages.config...
DEBUG: 2017-08-08 18:57:13Z - Executing: C:\Tools\nuget.exe install "C:\BuildMaster\Workspace\ThingCompany.InventoryManager\src\ThingCompany.InventoryManager\packages.config" -OutputDirectory "C:\BuildMaster\Workspace\ThingCompany.InventoryManager\src\packages"
DEBUG: 2017-08-08 18:57:13Z - Feeds used:
DEBUG: 2017-08-08 18:57:13Z -   C:\Windows\system32\config\systemprofile\.nuget\packages\
DEBUG: 2017-08-08 18:57:13Z -   https://api.nuget.org/v3/index.json
DEBUG: 2017-08-08 18:57:13Z - Restoring NuGet package ThingCompany.Services.1.0.6246.42730.
DEBUG: 2017-08-08 18:57:13Z - Restoring NuGet package ThingCompany.Common.1.0.6424.2156.
DEBUG: 2017-08-08 18:57:14Z -   GET https://api.nuget.org/v3-flatcontainer/ThingCompany.common/1.0.6424.2156/ThingCompany.common.1.0.6424.2156.nupkg
DEBUG: 2017-08-08 18:57:14Z -   GET https://api.nuget.org/v3-flatcontainer/ThingCompany.services/1.0.6246.42730/ThingCompany.services.1.0.6246.42730.nupkg
DEBUG: 2017-08-08 18:57:14Z -   NotFound https://api.nuget.org/v3-flatcontainer/ThingCompany.services/1.0.6246.42730/ThingCompany.services.1.0.6246.42730.nupkg 159ms
DEBUG: 2017-08-08 18:57:14Z - WARNING: Unable to find version '1.0.6246.42730' of package 'ThingCompany.Services'.
DEBUG: 2017-08-08 18:57:14Z -   C:\Windows\system32\config\systemprofile\.nuget\packages\: Package 'ThingCompany.Services.1.0.6246.42730' is not found on source 'C:\Windows\system32\config\systemprofile\.nuget\packages\'.
DEBUG: 2017-08-08 18:57:14Z -   https://api.nuget.org/v3/index.json: Package 'ThingCompany.Services.1.0.6246.42730' is not found on source 'https://api.nuget.org/v3/index.json'.
DEBUG: 2017-08-08 18:57:14Z -   NotFound https://api.nuget.org/v3-flatcontainer/ThingCompany.common/1.0.6424.2156/ThingCompany.common.1.0.6424.2156.nupkg 310ms
DEBUG: 2017-08-08 18:57:14Z - WARNING: Unable to find version '1.0.6424.2156' of package 'ThingCompany.Common'.
DEBUG: 2017-08-08 18:57:14Z -   C:\Windows\system32\config\systemprofile\.nuget\packages\: Package 'ThingCompany.Common.1.0.6424.2156' is not found on source 'C:\Windows\system32\config\systemprofile\.nuget\packages\'.
DEBUG: 2017-08-08 18:57:14Z -   https://api.nuget.org/v3/index.json: Package 'ThingCompany.Common.1.0.6424.2156' is not found on source 'https://api.nuget.org/v3/index.json'.
INFO : 2017-08-08 18:57:14Z - Done installing packages!
DEBUG: 2017-08-08 18:57:14Z - Cleaning up...
DEBUG: 2017-08-08 18:57:14Z - Deleting C:\BuildMaster\_SVCTMP\_E1036 on localhost...
DEBUG: 2017-08-08 18:57:14Z - C:\BuildMaster\_SVCTMP\_E1036 on localhost deleted.
DEBUG: 2017-08-08 18:57:14Z - Cleanup complete.
`

**Comment by mattkenn4545** [comment]
This is within a try/except block
