### ISSUE TITLE
PublishPackageOperation.cs package name does not handle wildcards

### ISSUE THREAD

**Issue by mattkenn4545** [Inedo/bmx-nuget#22]
I'm attempting to push nuget packages that have some dynamic sections to their file names (version/build etc..) so I tried to set package name to `packages\*.nupkg` however this results in 'does not exist'.  Looking at the code I think package name should allow wildcard expansion. 

Something like https://stackoverflow.com/questions/381366/is-there-a-wildcard-expansion-option-for-net-apps

**Comment by whatatripp** [comment]
We don't do this sort of wildcard expansion on arguments like this; we do have file masking, which allows you to search for files across directories in some operations.

One way to accomplish this in the Inedo Execution engine would be using a variable function or a powershell snippet that iterates *.nupkg files in a for-each loop.
