### ISSUE TITLE
X-NuGet-ApiKey is not the correct header for pushing package

### ISSUE THREAD

**Issue by mattkenn4545** [Inedo/bmx-nuget#23]
See http://inedo.com/support/documentation/proget/administration/security#api-keys

It should be 'X-ApiKey'

**Comment by whatatripp** [comment]
X-ApiKey is only used by ProGet, and APIs we design requests (like promotion, etc), but not necessarily APIs we implement (like NuGet, npm, etc) .

X-NuGet-ApiKey is used by NuGet servers (including ProGet); it's part of the NuGet protocol, which we don't document as part of ProGet (we just implement it).
